import type { Metadata } from "next";
import "./globals.css";

import { getAuthUser } from "@/app/lib/get-auth-user";
import { Toaster } from "react-hot-toast";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { AppProvider } from "@/app/context/AppContext";

const navItems = [
  {
    label: "Home",
    href: "/",
    exact: true,
  },
  {
    label: "Dashboard",
    href: "/dashboard",
    exact: false,
  },
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const authUser = await getAuthUser();

  return (
    <html lang="en">
      <body>
        <Toaster />
        <AppProvider authUser={authUser}>
          <Header
            heading="Next Strapi Auth"
            navItems={navItems}
          />
          <main className="py-12 min-h-screen bg-slate-800">
            <div className="container mx-auto">{children}</div>
          </main>
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
